name: point_of_sale
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  badges: ^3.1.2
  universal_html: ^2.2.4
  syncfusion_flutter_datagrid: ^26.1.35
  syncfusion_flutter_charts: ^26.1.35
  syncfusion_localizations: ^26.1.35
  quickalert: ^1.1.0
  intl: ^0.19.0
  number_to_vietnamese_words: ^1.0.1+1
  mask_text_input_formatter: ^2.9.0
  syncfusion_flutter_pdf:
  printing: ^5.12.0
  syncfusion_flutter_datepicker: ^26.1.39
  qr_code_scanner: ^1.0.1
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

#  flutter_launcher_icons: ^0.13.1

#flutter_launcher_icons:
#  android: true
#  image_path: "assets/images/logo.png"
#  min_sdk_android: 24

flutter:
  uses-material-design: true

  assets:
    - assets/images/
#    - assets/icons/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf